SELECT
  PF.CPF AS CPF
  ,P.NOME AS NOME
  ,PF.SEXO
  ,PF.TEMPOEMPREGADO
  ,PF.TEMPOMORADIAANOS
  ,PF.ESTADONATAL
  ,PF.CIDADENATAL
  ,PF.IDESCOLARIDADE
  ,PF.IDESTADOCIVIL
  ,PF.IDPROFISSAO
  ,PF.IDMORADIA
  ,PF.IDOCUPACAO
  ,PF.DATAADMISSAOPROFISSAO
  ,COALESCE(CTPF.NUM_DEPENDENTES, 0) NUM_DEPENDENTES
  ,COALESCE(CTPF.NUM_FILHOS, 0) AS NUM_FILHOS
  ,CTPF.POSSUIVEICULO
  ,Sum(LCC.VALOR) AS VLR_ENTRADA
  ,TC.DATACADASTRO
  ,CC.DATAINICIOATRASO
  ,TLC.LIMITEAPLICADO AS "LIMITE"
  ,Trunc(SYSDATE) - CC.DATAINICIOATRASO AS DIAS_ATRASO
FROM
  T_PESSOAFISICA PF
INNER JOIN
  T_CLIENTETITULARPESSOAFISICA CTPF
ON
  PF.IDPESSOAFISICA = CTPF.IDCLIENTETITULARPESSOAFISICA
INNER JOIN
  T_CLIENTEPESSOAFISICA CPF
ON
  CPF.IDCLIENTEPESSOAFISICA = CTPF.IDCLIENTETITULARPESSOAFISICA
INNER JOIN
  T_CLIENTECOBRANCA CC
ON
  CC.IDCLIENTETITULARPESSOAFISICA = CTPF.IDCLIENTETITULARPESSOAFISICA
INNER JOIN
  T_CADASTRO TC
ON
  TC.IDCADASTRO = PF.IDPESSOAFISICA
INNER JOIN
  T_PESSOA P
ON
  P.IDPESSOA = CTPF.IDCLIENTETITULARPESSOAFISICA
INNER JOIN
  T_LOJA L
ON
  L.IDLOJA = CTPF.IDLOJACADASTRO
INNER JOIN
  T_LIMITECREDITO TLC
ON
  TLC.IDCLIENTETITULARPESSOAFISICA = CTPF.IDCLIENTETITULARPESSOAFISICA
INNER JOIN
  T_LANCAMENTOCOBRANCACREDIT LCC
ON
  LCC.IDCLIENTECOBRANCA = CC.IDCLIENTECOBRANCA
  AND LCC.IDCLIENTECOBRANCA = CC.IDCLIENTECOBRANCA
WHERE
  CC.STATUS <> 'I'
  AND TC.DATACADASTRO >= '01/01/17'
  AND Trunc(SYSDATE) - CC.DATAINICIOATRASO > 90 -- 9.239
  AND NOT EXISTS (SELECT 'X' FROM T_PAGAMENTO P WHERE P.IDCLIENTETITULARPESSOAFISICA = CTPF.IDCLIENTETITULARPESSOAFISICA AND STATUS = 'N' AND MEIOTRANSACAO <> 'C')
  AND NOT EXISTS (SELECT 'X' FROM T_PAGAMENTOBOLETO P WHERE P.IDCLIENTETITULARPESSOAFISICA = CTPF.IDCLIENTETITULARPESSOAFISICA AND STATUS = 'N')
GROUP BY
  PF.CPF
  ,P.NOME
  ,PF.SEXO
  ,PF.TEMPOEMPREGADO
  ,PF.TEMPOMORADIAANOS
  ,PF.ESTADONATAL
  ,PF.CIDADENATAL
  ,PF.IDESCOLARIDADE
  ,PF.IDESTADOCIVIL
  ,PF.IDPROFISSAO
  ,PF.IDMORADIA
  ,PF.IDOCUPACAO
  ,PF.DATAADMISSAOPROFISSAO
  ,TC.DATACADASTRO
  ,CC.DATAINICIOATRASO
  ,CTPF.NUM_DEPENDENTES
  ,CTPF.NUM_FILHOS
  ,TLC.LIMITEAPLICADO
ORDER BY
  TC.DATACADASTRO
;