SELECT * FROM ALL_TABLES WHERE TABLE_NAME LIKE '%OCUPACAO%';

SELECT * FROM T_CADASTRO;

SELECT * FROM T_PESSOAFISICA;
SELECT * FROM T_ESCOLARIDADE;
SELECT * FROM T_OCUPACAO;
SELECT * FROM T_CLIENTETITULARPESSOAFISICA;
SELECT * FROM T_CLIENTEPESSOAFISICA;
SELECT * FROM T_PESSOA;
SELECT * FROM T_LOJA;
SELECT * FROM T_LIMITECREDITO;